### ISSUE TITLE
:bug: TypeError: cannot pickle `sqlite3.Connection` object

### ISSUE THREAD

**Issue by nicolay-r** [nicolay-r/ARElight#147]
This problem caused by type: 
`torch.utils.data.dataloader.DataLoader`
here:
https://github.com/nicolay-r/ARElight/blob/e18e7441f2964c4cac3e1feaf4f3d12e3b0520ab/arelight/pipelines/items/inference_bert_opennre.py#L125

Raised #149 related issue.
- [x] #149 

The most similar issue mentioned there: 
https://discuss.pytorch.org/t/dataloader-multiprocessing-error-cant-pickle-odict-keys-objects-when-num-workers-0/43951
which navigates us to:
https://github.com/pytorch/vision/issues/689

from where as we can see, we got no control over the related parameter (its value binded to `8`):
https://github.com/nicolay-r/ARElight/blob/e18e7441f2964c4cac3e1feaf4f3d12e3b0520ab/arelight/third_party/torch.py#L89-L97

```
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/kmax/PycharmProjects/ARElight-main/arelight/run/infer.py", line 328, in <module>
    BasePipelineLauncher.run(pipeline=pipeline, pipeline_ctx=PipelineResult(merge_dictionaries(settings)),
  File "/Users/kmax/PycharmProjects/ARElight-main/venv/lib/python3.9/site-packages/arekit/common/pipeline/base.py", line 18, in run
    item_result = item.apply(input_data=input_data, pipeline_ctx=pipeline_ctx)
  File "/Users/kmax/PycharmProjects/ARElight-main/venv/lib/python3.9/site-packages/arekit/common/pipeline/items/base.py", line 48, in apply
    output_data = self.apply_core(input_data=input_data, pipeline_ctx=pipeline_ctx)
  File "/Users/kmax/PycharmProjects/ARElight-main/arelight/pipelines/items/inference_writer.py", line 31, in apply_core
    self.__writer.write(header=header, contents_it=contents_it,
  File "/Users/kmax/PycharmProjects/ARElight-main/arelight/predict/writer_sqlite3.py", line 21, in write
    SQLiteProvider.write(
  File "/Users/kmax/PycharmProjects/ARElight-main/venv/lib/python3.9/site-packages/arekit/common/service/sqlite.py", line 26, in write
    for uid, data in data_it:
  File "/Users/kmax/PycharmProjects/ARElight-main/venv/lib/python3.9/site-packages/tqdm/std.py", line 1195, in iter
    for obj in iterable:
  File "/Users/kmax/PycharmProjects/ARElight-main/arelight/predict/provider.py", line 16, in __iter_contents
    for sample_id, uint_label in sample_id_with_uint_labels_iter:
  File "/Users/kmax/PycharmProjects/ARElight-main/arelight/pipelines/items/inference_bert_opennre.py", line 125, in iter_results
    for iter, data in enumerate(eval_loader):
  File "/Users/kmax/PycharmProjects/ARElight-main/venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 441, in iter
    @property
  File "/Users/kmax/PycharmProjects/ARElight-main/venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 388, in _get_iterator
    def multiprocessing_context(self, multiprocessing_context):
  File "/Users/kmax/PycharmProjects/ARElight-main/venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1042, in init
    self._data_queue = queue.Queue()  # type: ignore[var-annotated]
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in init
    super().__init__(process_obj)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_fork.py", line 19, in init
    self._launch(process_obj)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'sqlite3.Connection' object
```

**Comment by nicolay-r** [comment]
Fixed: could be reproduced with no issues on Mac
